---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordering-api
  labels:
    app: ordering-api
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: ordering-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ordering-api
    spec:
      containers:
      - name: ordering-api
        image: localhost:6000/ordering-api:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: ordering-api-env
      terminationGracePeriodSeconds: 180