---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-processor
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: payment-processor
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: payment-processor
    spec:
      containers:
      - name: payment-processor
        image: payment-processor:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: payment-processor-env
        - secretRef:
            name: payment-processor-secrets
      terminationGracePeriodSeconds: 180