resources:
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: webapp-env
  literals:
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY=in_memory
    - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    - HTTP_PORTS=8080
    - services__basket-api__http__0=http://basket-api:8080
    - services__catalog-api__http__0=http://catalog-api:8080
    - services__ordering-api__http__0=http://ordering-api:8080
    - DisableAuth=true
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
    - OTEL_EXPORTER_OTLP_HEADERS=x-otlp-api-key=bd556687-b71b-4065-95bb-f01077fed6cb1c4ef63a-bc26-4a4c-b29b-f6f4479a4ec6
    - OTEL_SERVICE_NAME=webapp
    - ASPNETCORE_URLS=http://+:8080;

secretGenerator:
- name: webapp-secrets
  envs:
  - .webapp.secrets
