resources:
- deployment.yml
- service.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: mobile-bff-env
  literals:
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true
    - services__catalog-api__0=http://catalog-api:8080
    - services__catalog-api__1=https://catalog-api:8443
    - services__identity-api__0=http://identity-api:8080
    - services__identity-api__1=https://identity-api:8443
    - ASPNETCORE_URLS=http://+:8080

