resources:
- deployment.yml
- service.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: catalog-api-env
  literals:
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true
    - ASPNETCORE_URLS=http://+:8080

secretGenerator:
- name: catalog-api-secrets
  envs:
  - .catalog-api.secrets
