---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhooks-api
  labels:
    app: webhooks-api
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: webhooks-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webhooks-api
    spec:
      containers:
      - name: webhooks-api
        image: localhost:6000/webhooks-api:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: webhooks-api-env
        - secretRef:
            name: webhooks-api-secrets
      terminationGracePeriodSeconds: 180