---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhooks-api
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: webhooks-api
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: webhooks-api
    spec:
      containers:
      - name: webhooks-api
        image: webhooks-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: webhooks-api-env
        - secretRef:
            name: webhooks-api-secrets
      terminationGracePeriodSeconds: 180